### ISSUE TITLE
Difference between Apache-Avro-Core and Microsoft-Avro-Core

### ISSUE THREAD

**Issue by robvanpamel** [welly87/Apache-Avro-Core#1]
Hi, 

I'm new to AVRO and i'm starting a new project in .NET CORE. For this i'm wondering if there is a fundamental difference between the Apache-Avro-Core version and the Microsoft-Avro-Core implementation you provided for .NET CORE support?

Are both of them supporting the same AVRO version or why do we need 2? 

Kind regards and thanks for your assistance!

**Comment by welly87** [comment]
yes it supported the same avro version. 

the difference is microsoft and apache create different open source project around that. 

if you want to start with schema then it's better using apache one, if you want to start defining with class please start with microsoft one

for performance please use microsoft avro one as it using expression tree for faster performance
